### ISSUE TITLE
Feature Request - Trump Tweet Listener

### ISSUE THREAD

**Issue by jayrav13** [trumptax/trumptax.me#6]
Listen for @realDonaldTrump tweets and auto-reply with the current amount of US Taxpayer $$ spent on him.

May require some script component, making this a non-100% front-end venture, but a cool thought. Will skyrocket # of followers on Twitter as well.

**Comment by trumptax** [comment]
This is such a good idea.

**Comment by trumptax** [comment]
I wonder if we could do this through some combination of IFTTT and a service to scrape text out of the rendered HTML... hmmm....

**Comment by jayrav13** [comment]
I tried doing this actually :) Unfortunately because the values are rendered in JS, I couldn't capture them with traditional HTTP request + parse :(

**Comment by trumptax** [comment]
It may be possible to do something through TravisCI. Something like:

* New tweet detected
* Kick off Travis job, which runs PhantomJS
* Phantom compiles and runs the site and either takes a screenshot or scrapes the HTML
* Result is used in a new tweet to Tangerine Tyant

**Comment by trumptax** [comment]
@jayrav13 – I've started working through an API server which can scrape trumptax.me for both a screenshot and the current value text: https://github.com/trumptax/trumptax-api/blob/master/routes/index.js#L19

The server itself works great. Trying to get it up and running on zeit.co – they may not support nightmare.js though. I need to do some debugging.

Once the API is up and running there should be a way to use IFTTT to:

* Detect new tweets
* Pull data from the API
* Publish a tweet response

**Comment by dandean** [comment]
I've got this working via IFTTT, now.sh, and a tiny express app.

* IFTTT detects a new tweet
* IFTTT issues a request to the tiny express app here: https://github.com/trumptax/trumptax-api/blob/master/routes/index.js#L41-L75
* The express up calculates the current tax burden using this extracted module: https://github.com/trumptax/trumptax-calculator
* The express app responds to the tweet using the calculated tax burden:

![image](https://cloud.githubusercontent.com/assets/18332/23341856/5deb24f4-fc04-11e6-95a4-2919fd145a0f.png)

**Comment by jayrav13** [comment]
Awesome!! I imagine you have the express app hosted somewhere?
